config/routes.rb
Rails.application.routes.draw do
  match 'search' => 'blogs#index', via: [:get, :post], as: :search
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'blogs#index'
  resources :blogs do
    resources :votes, only: [:create, :destroy]
  end
  get 'tags/:tag', to: 'blogs#index', as: :tags
  resources :users, only: [:show, :index]

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  acts_as_taggable
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes

  # Enrols user to the course
  def voted(user)
    self.votes.where(user_id: [user.id]).any?
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: {medium: "300x300#"}, default_url: ENV["USER_PLACEHOLDER"]
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  friendly_id :name, use: :slugged

  has_many :blogs, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :blogs, through: :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_filter :set_search

  # rescue from pundit by going the function
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  # alert user for unauthorized usage
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def set_search
    @q=Blog.search(params[:q])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    if params[:q].present?
      @q = Blog.ransack(params[:q])
      @blogs = @q.result(distinct: true).order('created_at DESC')
    elsif params[:tag].present?
      @blogs = Blog.tagged_with(params[:tag]).order('created_at DESC')
    else
      @blogs = Blog.all.order('created_at DESC')
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    authorize @blog
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    authorize @blog
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    authorize @blog
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :publish, :tag_list, :image_url)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  # Devise parameter allowed for controller during signup
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Devise parameter allowed for controller during update account
  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :website, :twitter)
  end

  # Allow Devise user to update the account without putting current password
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  before_action :set_user, only: :show

  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
    if params[:likes].present?
      @blogs = @user.blogs.where.not(user: @user)
    else
      @blogs = Blog.where(user: @user).all
    end
  end

  private
  def set_user
    @user = User.friendly.find(params[:id])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog

  def create
    @vote = Vote.new
    @vote.blog = @blog
    @vote.user = current_user
    @vote.save
    redirect_to :back
  end

  def destroy
    @vote = @blog.votes.find(params[:id])
    @vote.destroy
    redirect_to :back
  end


  private
  def set_blog
    @blog = Blog.friendly.find(params[:blog_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<!-- Handling each blog separate -->
<% @blogs.each do |blog| %>
    <%= link_to blog_path(blog), class: "black-text" do %>
        <div class="col s12 m4">
          <div class="card">
            <div class="card-content black-text" style="min-height: 350px; max-height: 350px; overflow: scroll">
              <span class="card-title black-text"><strong><%= blog.title.truncate(20) %></strong></span>

              <!-- Vote add/remove -->
              <% if user_signed_in? && blog.voted(current_user) %>
                  <div class="right">
                    <% if blog.user == current_user %>
                        <h5><i class="fa fa-heart" style="color: #FF0000;"></i> <%= blog.votes.count %></h5>
                    <% else %>
                    <%= link_to blog_vote_path(blog,blog.votes.where(user_id: current_user.id).first.id), method: :delete do %>
                        <h5><i class="fa fa-heart" style="color: #FF0000;"></i> <%= blog.votes.count %></h5>
                    <% end %>
                    <% end %>
                  </div>
              <% else %>
                  <div class="right">
                    <% if blog.user == current_user %>
                        <h5><i class="fa fa-heart-o" style="color: #FF0000"></i> <%= blog.votes.count %></h5>
                    <% else %>
                    <%= link_to blog_votes_path(blog), method: :post do %>
                        <h5><i class="fa fa-heart-o" style="color: #FF0000"></i> <%= blog.votes.count %></h5>
                    <% end %>
                    <% end %>
                  </div>
              <% end %>

              <% require 'rubygems' %>
              <% require 'nokogiri' %>
              <div><%= Nokogiri::HTML(blog.content).text.truncate(250, separator: ' ') %></div>
              <hr/>
              <small>Created by <em><%= link_to blog.user.name, user_path(blog.user) %></em>, <%= time_ago_in_words(blog.created_at) %> ago</small><br/>

              <!-- Blog Tags -->
              <% blog.tags.each do |tag| %>
                  <%= link_to tags_path(tag.name) do %>
                      <div class="chip">
                        <%= tag.name %>
                      </div>
                  <% end %>
              <% end %>

            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/blogs/_form.html.erb
<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <%= form_for(@blog) do |f| %>
        <!-- blog title -->
        <div class="input-field">
          <%= f.label :title %>
          <%= f.text_field :title, required: true, autofocus: true %>
        </div>

        <!-- blog content -->
        <div class="input-field">
        <%= f.cktext_area :content, required: true, class: "materialize-textarea" %>
        </div>

        <!-- blog tags -->
        <div class="input-field">
        <%= f.label :tag_list %>
        <%= f.text_field :tag_list, :"data-role" => "materialtags", value: @blog.tag_list.to_s %>
        </div>

        <!-- blog publish -->
        <div class="input-field">
          <%= f.check_box :publish, class: "filled-in" %>
          <%= f.label :publish %>
        </div>

        <!-- blog image_url for meta -->
        <div class="input-field">
        <%= f.label :image_url, "Optional Image url for meta" %>
        <%= f.text_field :image_url %>
        </div>

        <!-- Submit form -->
        <div class="input-field center">
          <%= f.submit button, class: "btn" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
    <h1 class="center">Edit <%= @blog.title.truncate(15) %></h1>

    <%= render partial:'form', locals: {button: "Save Blog"} %>
</div>

app/views/blogs/index.html.erb
<%
   meta title: 'Home',
        description: 'Bloggy app is a clone of Medium App built in Ruby on Rails with WSIYMG editor',
        keywords: %w(RubyOnRails Rails Medium Bloggy blog),
        rel: {
                author: "http://www.sulmanbaig.com",
                publisher: "https://codelit.com"
        },
        og: {
                title: 'Home | Bloggy - Medium Clone',
                image: "https://codelit.s3.amazonaws.com/photos/images/000/000/010/original/cup-mug-desk-office.jpg?1445262634",
                site_name: "Bloggy",
                url: root_url,
                description: 'Bloggy app is a clone of Medium App built in Ruby on Rails with WSIYMG editor',
                type: "blog",
                locale: "en_US"
        },
        fb: {
                app_id: "429015597309000"
        },
        twitter: {
                card: "summary",
                title: "Home | Bloggy - Medium Clone",
                site: "@codelitweb",
                image: "https://codelit.s3.amazonaws.com/photos/images/000/000/010/original/cup-mug-desk-office.jpg?1445262634",
                description: 'Bloggy app is a clone of Medium App built in Ruby on Rails with WSIYMG editor'
        }
%>
<div class="container">
  <!-- Fixed New blog button -->
  <% if user_signed_in? %>
  <div class="fixed-action-btn" style="top: 50px; right: 24px;">
    <a class="btn-floating btn-large red" href="<%= new_blog_path %>">
      <i class="large material-icons">add</i>
    </a>
  </div>
  <% end %>

  <!-- Header of index-->
  <h1 class="center">Bloggy</h1>
  <!-- Go to www.addthis.com/dashboard to customize your tools -->
  <div class="addthis_sharing_toolbox center"></div>

  <!-- Indexes -->
  <div class="row">
    <%= render 'blogs/blog' %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
<h1 class="center">New Blog</h1>

<%= render partial:'form', locals: {button: "Create Blog"} %>
</div>

app/views/blogs/show.html.erb
<% require 'rubygems' %>
<% require 'nokogiri' %>
<%
   meta title: @blog.title,
        description: Nokogiri::HTML(@blog.content).text.truncate(150, separator: ' '),
        keywords: %{#{@blog.tag_list}},
        rel: {
                author: @blog.user.website,
                publisher: root_url
        },
        og: {
                title: "#{@blog.title} | Bloggy - Medium Clone",
                image: @blog.image_url,
                site_name: "Bloggy",
                url: blog_url(@blog),
                description: Nokogiri::HTML(@blog.content).text.truncate(150, separator: ' '),
                type: "article",
                locale: "en_US"
        },
        fb: {
                app_id: "429015597309000"
        },
        twitter: {
                card: "summary",
                title: "#{@blog.title} | Bloggy - Medium Clone",
                site: @blog.user.twitter,
                image: @blog.image_url,
                description: Nokogiri::HTML(@blog.content).text.truncate(150, separator: ' ')
        }
%>
<div class="container">
  <div class="row">
    <div class="col s12">
      <div class="card-panel">
        <!-- Go to www.addthis.com/dashboard to customize your tools -->
        <div class="addthis_sharing_toolbox center"></div>

        <h1 class="center"><%= @blog.title %></h1>

        <!-- Vote add/remove -->
        <% if user_signed_in? && @blog.voted(current_user) %>
            <div class="center">
              <% if @blog.user == current_user %>
                  <h4><i class="fa fa-heart" style="color: #FF0000;"></i> <%= @blog.votes.count %></h4>
              <% else %>
                  <%= link_to blog_vote_path(@blog,@blog.votes.where(user_id: current_user.id).first.id), method: :delete do %>
                      <h4><i class="fa fa-heart" style="color: #FF0000;"></i> <%= @blog.votes.count %></h4>
                  <% end %>
              <% end %>
            </div>
        <% else %>
            <div class="center">
              <% if @blog.user == current_user %>
                  <h4><i class="fa fa-heart-o" style="color: #FF0000"></i> <%= @blog.votes.count %></h4>
              <% else %>
                  <%= link_to blog_votes_path(@blog), method: :post do %>
                      <h4><i class="fa fa-heart-o" style="color: #FF0000"></i> <%= @blog.votes.count %></h4>
                  <% end %>
              <% end %>
            </div>
        <% end %>

        <div class="center">
        <small class="center">Created by <em><%= @blog.user.name %></em>, <%= time_ago_in_words(@blog.created_at) %> ago</small>
        </div>

        <!-- If user is signed in and author of the blog -->
        <% if user_signed_in? && @blog.user == current_user %>
        <div class="center">
          <%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_blog_path(@blog), class: "btn blue" %>
          <%= link_to '<i class="material-icons">delete</i>'.html_safe, @blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn red" %>
        </div>
        <% end %>

        <hr/>
        <p><%= raw @blog.content %></p>
        <hr/>

        <!-- Blog Tags -->
        <% @blog.tags.each do |tag| %>
            <div class="chip">
              <%= link_to tag.name, tags_path(tag.name) %>
            </div>
        <% end %>

      </div>
      <div class="card-panel">
        <h3 class="center">Discussions</h3>

        <!-- Disqus Comments -->
        <div id="disqus_thread"></div>
        <script>
            /**
             *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
             *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
             */
             var disqus_config = function () {
             this.page.url = "<%= blog_url(@blog) %>";  // Replace PAGE_URL with your page's canonical URL variable
             this.page.identifier = "bloggy_<%= @blog.id %>"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
             };
            (function() {  // DON'T EDIT BELOW THIS LINE
                var d = document, s = d.createElement('script');

                s.src = '//bloggy-codelit.disqus.com/embed.js';

                s.setAttribute('data-timestamp', +new Date());
                (d.head || d.body).appendChild(s);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>


      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!-- Meta Data here -->
  <%=
      metamagic site: "Bloggy", title: [:title, :site], separator: " | "
  %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--Import Google Icon Font-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'shared/topNav' %>
    <main>
        <%= yield %>
    </main>
    <%= render 'shared/footer' %>

    <script id="dsq-count-scr" src="http://bloggy-codelit.disqus.com/count.js" async></script>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55a26c18411c32a4" async="async"></script>
</body>
</html>

app/views/shared/_footer.html.erb
<nav style="background-color: rgba(158, 158, 158, 0.21);">
  <div class="nav-wrapper">
    <a href="http://www.sulmanbaig.com" style="color: #9E9E9E; margin-right: 10px;" class="right">Copyright &copy; Sulman Baig</a>
  </div>
</nav>

app/views/shared/_navElements.html.erb
<li class="<%= "active" if controller_name == "blogs" %>"><%= link_to "Blogs", root_path %></li>
<% unless user_signed_in? %>
    <li class="<%= "active" if current_page?(new_user_session_path) %>"><%= link_to "Log In", new_user_session_path %></li>
    <li class="<%= "active" if current_page?(new_user_registration_path) %>"><%= link_to "Sign Up", new_user_registration_path %></li>
<% end %>

<!-- Dropdown Structure -->
<% if user_signed_in? %>
<ul id="dropdown1" class="dropdown-content">
  <li><a href="<%= user_path(current_user) %>">Profile</a></li>
  <li><a href="<%= edit_user_registration_path %>">Edit Profile</a></li>
  <li class="divider"></li>
  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
</ul>
<!-- Dropdown Structure -->
<ul id="dropdown2" class="dropdown-content">
  <li><a href="<%= user_path(current_user) %>">Profile</a></li>
  <li><a href="<%= edit_user_registration_path %>">Edit Profile</a></li>
  <li class="divider"></li>
  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
</ul>
<% end %>

app/views/shared/_topNav.html.erb
<nav style="background-color: #0089EC;">
  <div class="nav-wrapper">
    <a href="<%= root_path %>" class="brand-logo">Bloggy</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <div class="left hide-on-small-and-down", style="margin-left: 100px;">

        <%= search_form_for @q, url: search_path, html: { method: :post } do |f| %>
            <div class="input-field">
              <%= f.search_field :title_or_content_cont %>
              <label for="q_title_or_content_cont"><i class="material-icons">search</i></label>
              <i class="material-icons">close</i>
            </div>
        <% end %>

    </div>
    <ul class="right hide-on-med-and-down">
      <%= render "shared/navElements" %>
      <% if user_signed_in? %>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= image_tag current_user.avatar.url(:medium), alt: current_user.name, class: "circle responsive-img", style: "width: 25px; height: 25px;" %> <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <%= render "shared/navElements" %>
      <% if user_signed_in? %>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown2"><%= image_tag current_user.avatar.url(:medium), alt: current_user.name, class: "circle responsive-img", style: "width: 25px; height: 25px;" %> <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <div class="card-panel">
        <div class="row">
          <div class="col m4">
            <%= image_tag @user.avatar.url(:medium), alt: @user.name, style: "width: 150px; height: 150px;", class: "circle responsive-img" %>
          </div>
          <div class="col m8">
            <h3><%= @user.name %></h3>
            <p>Email: <%= link_to @user.email, "mailto:"+@user.email %></p>
            <% if @user.website.present? %>
                <p>Website: <%= link_to @user.website, @user.website, target: "_blank" %></p>
            <% end %>
            <% if @user.twitter.present? %>
                <p>twitter: <%= link_to @user.twitter, "https://twitter.com/"+@user.twitter.tr('@',''), target: "_blank" %></p>
            <% end %>
          </div>
        </div>
      </div>

      <div class="center">
        <%= link_to "Blogs", user_path(@user), class: "btn" %>
        <%= link_to "Likes", user_path(@user, likes: "true"), class: "btn" %>
      </div>

      <%= render 'blogs/blog' %>
    </div>
  </div>
</div>